In [141]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [142]:
import pandas as pd
import numpy as np

In [143]:
import pandas as pd
import numpy as np

# Create a 5x6 DataFrame
# Generate random floats for some columns and random integers for others
data = {
    'col1': np.random.rand(5) * 100,  # Floats
    'col2': np.random.randint(1, 100, 5),  # Integers
    'col3': np.random.rand(5) * 50,  # Floats
    'col4': np.random.randint(50, 150, 5),  # Integers
    'col5': np.random.rand(5) * 10,  # Floats
    'col6': np.random.randint(0, 10, 5)  # Integers
}
df = pd.DataFrame(data)
print(df)


        col1  col2       col3  col4      col5  col6
0  71.975423    89  21.406116   140  1.678233     7
1  25.849809    69   4.826546   113  3.674714     1
2  54.620732    47   6.357999   129  4.686736     6
3  40.730783    71  29.837265    99  6.542662     8
4  17.698462    96  11.300600    89  7.930897     5


In [144]:
df.apply(lambda x: x + 1)

,col1,col2,col3,col4,col5,col6
0,72.975423,90,22.406116,141,2.678233,8
1,26.849809,70,5.826546,114,4.674714,2
2,55.620732,48,7.357999,130,5.686736,7
3,41.730783,72,30.837265,100,7.542662,9
4,18.698462,97,12.300600,90,8.930897,6


In [145]:
df.apply(lambda x: x + 1, axis=0)
df.apply(lambda x: x + 1, axis=1)

,col1,col2,col3,col4,col5,col6
0,72.975423,90,22.406116,141,2.678233,8
1,26.849809,70,5.826546,114,4.674714,2
2,55.620732,48,7.357999,130,5.686736,7
3,41.730783,72,30.837265,100,7.542662,9
4,18.698462,97,12.300600,90,8.930897,6


,col1,col2,col3,col4,col5,col6
0,72.975423,90.0,22.406116,141.0,2.678233,8.0
1,26.849809,70.0,5.826546,114.0,4.674714,2.0
2,55.620732,48.0,7.357999,130.0,5.686736,7.0
3,41.730783,72.0,30.837265,100.0,7.542662,9.0
4,18.698462,97.0,12.300600,90.0,8.930897,6.0


In [146]:
df.apply(lambda x: x + 1, 0)

,col1,col2,col3,col4,col5,col6
0,72.975423,90,22.406116,141,2.678233,8
1,26.849809,70,5.826546,114,4.674714,2
2,55.620732,48,7.357999,130,5.686736,7
3,41.730783,72,30.837265,100,7.542662,9
4,18.698462,97,12.300600,90,8.930897,6


In [147]:
df.sum()
df.sum(0)
df.sum(1)

col1    210.875209
col2    372.000000
col3     73.728526
col4    570.000000
col5     24.513242
col6     27.000000
dtype: float64

col1    210.875209
col2    372.000000
col3     73.728526
col4    570.000000
col5     24.513242
col6     27.000000
dtype: float64

0    331.059773
1    217.351068
2    247.665466
3    255.110710
4    226.929960
dtype: float64

In [148]:
df.sum(axis=0)
df.sum(axis=1)

col1    210.875209
col2    372.000000
col3     73.728526
col4    570.000000
col5     24.513242
col6     27.000000
dtype: float64

0    331.059773
1    217.351068
2    247.665466
3    255.110710
4    226.929960
dtype: float64

In [149]:
df["total"] = df.loc[:, "col1":"col6"].sum(axis=1)
df

,col1,col2,col3,col4,col5,col6,total
0,71.975423,89,21.406116,140,1.678233,7,331.059773
1,25.849809,69,4.826546,113,3.674714,1,217.351068
2,54.620732,47,6.357999,129,4.686736,6,247.665466
3,40.730783,71,29.837265,99,6.542662,8,255.110710
4,17.698462,96,11.300600,89,7.930897,5,226.929960


In [150]:
df.mean()
df.mean(0)
df.mean(1)

col1      42.175042
col2      74.400000
col3      14.745705
col4     114.000000
col5       4.902648
col6       5.400000
total    255.623396
dtype: float64

col1      42.175042
col2      74.400000
col3      14.745705
col4     114.000000
col5       4.902648
col6       5.400000
total    255.623396
dtype: float64

0    94.588506
1    62.100305
2    70.761562
3    72.888774
4    64.837131
dtype: float64

In [151]:
df.mean(axis=0)
df.mean(axis=1)

col1      42.175042
col2      74.400000
col3      14.745705
col4     114.000000
col5       4.902648
col6       5.400000
total    255.623396
dtype: float64

0    94.588506
1    62.100305
2    70.761562
3    72.888774
4    64.837131
dtype: float64

In [152]:
df.min()
df.min(0)
df.min(1)

col1      17.698462
col2      47.000000
col3       4.826546
col4      89.000000
col5       1.678233
col6       1.000000
total    217.351068
dtype: float64

col1      17.698462
col2      47.000000
col3       4.826546
col4      89.000000
col5       1.678233
col6       1.000000
total    217.351068
dtype: float64

0    1.678233
1    1.000000
2    4.686736
3    6.542662
4    5.000000
dtype: float64

In [153]:
df.min(axis=0)
df.min(axis=1)

col1      17.698462
col2      47.000000
col3       4.826546
col4      89.000000
col5       1.678233
col6       1.000000
total    217.351068
dtype: float64

0    1.678233
1    1.000000
2    4.686736
3    6.542662
4    5.000000
dtype: float64

In [154]:
df2 = df.drop("total", axis=1)
df2

,col1,col2,col3,col4,col5,col6
0,71.975423,89,21.406116,140,1.678233,7
1,25.849809,69,4.826546,113,3.674714,1
2,54.620732,47,6.357999,129,4.686736,6
3,40.730783,71,29.837265,99,6.542662,8
4,17.698462,96,11.300600,89,7.930897,5


In [155]:
df2.loc["max_data"]=df2.loc[:, "col1":"col6"].max()
df2

,col1,col2,col3,col4,col5,col6
0,71.975423,89.0,21.406116,140.0,1.678233,7.0
1,25.849809,69.0,4.826546,113.0,3.674714,1.0
2,54.620732,47.0,6.357999,129.0,4.686736,6.0
3,40.730783,71.0,29.837265,99.0,6.542662,8.0
4,17.698462,96.0,11.300600,89.0,7.930897,5.0
max_data,71.975423,96.0,29.837265,140.0,7.930897,8.0


In [156]:
df2.iloc[0, 3] = np.nan
df2.iloc[3, 5] = np.nan
df2

,col1,col2,col3,col4,col5,col6
0,71.975423,89.0,21.406116,NaN,1.678233,7.0
1,25.849809,69.0,4.826546,113.0,3.674714,1.0
2,54.620732,47.0,6.357999,129.0,4.686736,6.0
3,40.730783,71.0,29.837265,99.0,6.542662,NaN
4,17.698462,96.0,11.300600,89.0,7.930897,5.0
max_data,71.975423,96.0,29.837265,140.0,7.930897,8.0


In [157]:
df2.dropna(axis=0)

,col1,col2,col3,col4,col5,col6
1,25.849809,69.0,4.826546,113.0,3.674714,1.0
2,54.620732,47.0,6.357999,129.0,4.686736,6.0
4,17.698462,96.0,11.300600,89.0,7.930897,5.0
max_data,71.975423,96.0,29.837265,140.0,7.930897,8.0


In [158]:
df2.dropna(axis=1)

,col1,col2,col3,col5
0,71.975423,89.0,21.406116,1.678233
1,25.849809,69.0,4.826546,3.674714
2,54.620732,47.0,6.357999,4.686736
3,40.730783,71.0,29.837265,6.542662
4,17.698462,96.0,11.300600,7.930897
max_data,71.975423,96.0,29.837265,7.930897


In [159]:
df2.fillna(0)

,col1,col2,col3,col4,col5,col6
0,71.975423,89.0,21.406116,0.0,1.678233,7.0
1,25.849809,69.0,4.826546,113.0,3.674714,1.0
2,54.620732,47.0,6.357999,129.0,4.686736,6.0
3,40.730783,71.0,29.837265,99.0,6.542662,0.0
4,17.698462,96.0,11.300600,89.0,7.930897,5.0
max_data,71.975423,96.0,29.837265,140.0,7.930897,8.0


In [160]:
df2.fillna(1)

,col1,col2,col3,col4,col5,col6
0,71.975423,89.0,21.406116,1.0,1.678233,7.0
1,25.849809,69.0,4.826546,113.0,3.674714,1.0
2,54.620732,47.0,6.357999,129.0,4.686736,6.0
3,40.730783,71.0,29.837265,99.0,6.542662,1.0
4,17.698462,96.0,11.300600,89.0,7.930897,5.0
max_data,71.975423,96.0,29.837265,140.0,7.930897,8.0


In [161]:
df2.fillna(0).astype(int)

,col1,col2,col3,col4,col5,col6
0,71,89,21,0,1,7
1,25,69,4,113,3,1
2,54,47,6,129,4,6
3,40,71,29,99,6,0
4,17,96,11,89,7,5
max_data,71,96,29,140,7,8


In [162]:
df2.fillna(0).astype(str)

,col1,col2,col3,col4,col5,col6
0,71.97542323569591,89.0,21.406116379869474,0.0,1.6782331070145573,7.0
1,25.84980864373988,69.0,4.826545783030628,113.0,3.674713686238469,1.0
2,54.6207319902158,47.0,6.357998585063873,129.0,4.686735841662192,6.0
3,40.73078322899452,71.0,29.837265448929788,99.0,6.542661822070913,0.0
4,17.698462366793656,96.0,11.300600030211793,89.0,7.930897437426204,5.0
max_data,71.97542323569591,96.0,29.837265448929788,140.0,7.930897437426204,8.0


In [163]:
df3 = df2.fillna(0).astype(str)
df3.astype(float).astype(int)

,col1,col2,col3,col4,col5,col6
0,71,89,21,0,1,7
1,25,69,4,113,3,1
2,54,47,6,129,4,6
3,40,71,29,99,6,0
4,17,96,11,89,7,5
max_data,71,96,29,140,7,8


In [164]:
df3 = pd.DataFrame({
'a':[1,3,4,3,4],
'b':[2,3,1,4,5],
'c':[1,5,2,4,4]
})
df3

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [165]:
np.sum([1,2,3])

np.int64(6)

In [166]:
np.sum(df3['a'])
np.sum(df3['b'])
np.sum(df3['c'])
for i in ['a','b','c'] :
    print(np.sum(df3[i]))
df3.apply(np.sum,0)
df3.apply(np.sum,1)

np.int64(15)

np.int64(15)

np.int64(16)

15
15
16


a    15
b    15
c    16
dtype: int64

0     4
1    11
2     7
3    11
4    13
dtype: int64

In [167]:
import seaborn as sns

In [168]:
titanic = sns.load_dataset('titanic')
titanic.head() # 처음 5행 출력
titanic.tail() # 마지막 5행 출력
#itanic.head(2) # 처음 2행 출력

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [169]:
titanic[['alive','sex','class']].apply(pd.value_counts,0)

/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_42860/2950698262.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  titanic[['alive','sex','class']].apply(pd.value_counts,0)
/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_42860/2950698262.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  titanic[['alive','sex','class']].apply(pd.value_counts,0)
/var/folders/7l/yp5d25zx7nb_92wbp8w2b0dw0000gn/T/ipykernel_42860/2950698262.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  titanic[['alive','sex','class']].apply(pd.value_counts,0)


,alive,sex,class
First,NaN,NaN,216.0
Second,NaN,NaN,184.0
Third,NaN,NaN,491.0
female,NaN,314.0,NaN
male,NaN,577.0,NaN
no,549.0,NaN,NaN
yes,342.0,NaN,NaN


In [170]:
def diff(x) : # x는 시리즈
    return x.max() - x.min()

In [171]:
df3
# 함수 호출
diff(df3['a'])
diff(df3['b'])
diff(df3['c'])

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


3

4

4

In [172]:
# apply 함수 적용
df3.apply(diff,0)
df3.apply(diff,1)

a    3
b    4
c    4
dtype: int64

0    1
1    2
2    3
3    1
4    1
dtype: int64

In [173]:
pd.Series(3)
pd.Series(3).max()

0    3
dtype: int64

3

In [174]:
(lambda x : x.max()-x.min())(df3['a'])
(lambda x : x.max()-x.min())(df3)

3

a    3
b    4
c    4
dtype: int64

In [175]:
df3.apply(lambda x : x.max()-x.min(),0)
df3.apply(lambda x : x.max()-x.min(),1)

a    3
b    4
c    4
dtype: int64

0    1
1    2
2    3
3    1
4    1
dtype: int64

In [176]:
df3.max(axis=0)- df3.min(axis=0)
df3.max(axis=1)- df3.min(axis=1)

a    3
b    4
c    4
dtype: int64

0    1
1    2
2    3
3    1
4    1
dtype: int64

In [177]:
np.square([1,2,3])
df3
df3.apply(np.square,0)
df3.apply(np.square,1)

array([1, 4, 9])

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


,a,b,c
0,1,4,1
1,9,9,25
2,16,1,4
3,9,16,16
4,16,25,16


,a,b,c
0,1,4,1
1,9,9,25
2,16,1,4
3,9,16,16
4,16,25,16


In [178]:
np.square(df3)

,a,b,c
0,1,4,1
1,9,9,25
2,16,1,4
3,9,16,16
4,16,25,16


In [179]:
ages=[0,0.5,4,6,4,5,2,10,21,23,37,15,38,31,61,20,41,31,100]

In [180]:
# data : 구간 나눌 실제 값, bins : 구간 경계값, label: 카테고리값
data = ages
# 구간 경계값
# 구간 최소값 < 구간 <= 구간 최대값
bins = [0,4,18,25,35,60,100]
# 0~4 구간 : 영유아 0살 < 영유아 <=4
# 각 구간의 이름 : labels - 카테고리명
# 순서는 구간(bins)의 순서와 동일해야 함
labels = ['영유아','미성년자','청년','중년','장년','노년']

In [181]:
len(data)
cats = pd.cut(data,bins,labels=labels)
cats
type(cats)

19

[NaN, '영유아', '영유아', '미성년자', '영유아', ..., '노년', '청년', '장년', '중년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

pandas.core.arrays.categorical.Categorical

In [182]:
cat_list = list(cats)
cat_list

[nan,
 '영유아',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '청년',
 '청년',
 '장년',
 '미성년자',
 '장년',
 '중년',
 '노년',
 '청년',
 '장년',
 '중년',
 '노년']

In [183]:
test = pd.DataFrame({'나이':ages,'연령대':cat_list})
test
test['연령대'].value_counts()

,나이,연령대
0,0.0,NaN
1,0.5,영유아
2,4.0,영유아
3,6.0,미성년자
4,4.0,영유아
5,5.0,미성년자
6,2.0,영유아
7,10.0,미성년자
8,21.0,청년
9,23.0,청년


연령대
영유아     4
미성년자    4
청년      3
장년      3
중년      2
노년      2
Name: count, dtype: int64

In [184]:
type(cats)
cats

pandas.core.arrays.categorical.Categorical

[NaN, '영유아', '영유아', '미성년자', '영유아', ..., '노년', '청년', '장년', '중년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [185]:
cats.categories # cats 변수내의 범주 index를 저장

Index(['영유아', '미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [186]:
cats.codes

array([-1,  0,  0,  1,  0,  1,  0,  1,  2,  2,  4,  1,  4,  3,  5,  2,  4,
        3,  5], dtype=int8)

In [187]:
qcuts = pd.qcut(data, 6, labels=labels)
qcuts

['영유아', '영유아', '미성년자', '청년', '미성년자', ..., '노년', '청년', '노년', '장년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [188]:
qcuts.codes

array([0, 0, 1, 2, 1, 1, 0, 2, 3, 3, 4, 2, 4, 4, 5, 2, 5, 4, 5],
      dtype=int8)

In [189]:
qcuts.value_counts()

영유아     3
미성년자    3
청년      4
중년      2
장년      4
노년      3
Name: count, dtype: int64

In [190]:
# 랜덤정수 20개를 생성하고 생성된 정수를 4개의 구간으로 나누시오.
# 각 구간의 label은 Q1,Q2,Q3,Q4 로 설정하시오.
#랜덤정수 생성 : 범위 0-19, size =20
#seed 설정해서 재 실행해도 랜덤정수가 변하지 않도록 생성
np.random.seed(2)
data = np.random.randint(20,size=20)
data
qcat = pd.qcut(data,4,labels=['Q1','Q2','Q3','Q4'])
qcat
qcat.value_counts()

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

['Q2', 'Q4', 'Q4', 'Q2', 'Q3', ..., 'Q1', 'Q1', 'Q1', 'Q3', 'Q3']
Length: 20
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

Q1    5
Q2    5
Q3    5
Q4    5
Name: count, dtype: int64

In [191]:
np.sort(data)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18])

In [192]:
df0 = pd.DataFrame(data, columns=['관측수'])
# df0
df0['범주']=qcat
df0

,관측수,범주
0,8,Q2
1,15,Q4
2,13,Q4
3,8,Q2
4,11,Q3
5,18,Q4
6,11,Q3
7,8,Q2
8,7,Q2
9,2,Q1


In [193]:
#예제 데이터프레임 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [194]:
# df3의 'a'열을 인덱스로 설정
df3.set_index('a') # 원본반영되지 않음
df3
df3.set_index('a',inplace=True) # 원본에 저장

,b,c
a,,
1,2,1
3,3,5
4,1,2
3,4,4
4,5,4


,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


In [195]:
df3
df3.loc[3]

,b,c
a,,
1,2,1
3,3,5
4,1,2
3,4,4
4,5,4


,b,c
a,,
3,3,5
3,4,4


In [196]:
# 기본 인덱스(제로베이스)로 인덱스 수정
df3.reset_index() # 인덱스 값은 df의 열 데이터로 추가
df3 #원본반영안됨

,a,b,c
0,1,2,1
1,3,3,5
2,4,1,2
3,3,4,4
4,4,5,4


,b,c
a,,
1,2,1
3,3,5
4,1,2
3,4,4
4,5,4


In [197]:
# 인덱스값이 관측값이 아니거나 불필요한 경우는 df의 열데이터로 추가되지 않게 해야함
# drop=True (기존 인덱스 삭제)
df3.reset_index(drop=True)

,b,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


In [198]:
df3.reset_index(drop=True,inplace=True)
df3

,b,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


In [199]:
# 행인덱스 값 변경
# df3의 인덱스 0 -> 1반으로 변경
# df3.rename(index={0:'1반'}) # 원본반영 안됨
# df3
df3.rename(index={0:'1반',1:'2반'})

,b,c
1반,2,1
2반,3,5
2,1,2
3,4,4
4,5,4


In [200]:
# 컬럼명 변경
df3.rename(columns={'b':'학생'},inplace=True)
df3

,학생,c
0,2,1
1,3,5
2,1,2
3,4,4
4,5,4


In [201]:
### 리스트 내포 for 문
a=[1,2,3,4]
# 위 a 리스트의 각 원소에 2배한 원소값을 만들고 리스트로 저장하시오. 반복문을 사용할 것
# result =[2,4,6,8]
a=[1,2,3,4]
result = [] # 빈리스트 생성
for num in a :
    result.append(num*2)
result

[2, 4, 6, 8]

In [202]:
result = [num * 3 for num in a]
result

[3, 6, 9, 12]

In [203]:
# 반복문 이용
test = []
for i in range(1,5) :
    test.append('id_'+str(i))
test

['id_1', 'id_2', 'id_3', 'id_4']

In [204]:
test = ['id_'+str(i) for i in range(1,5) ]
test

['id_1', 'id_2', 'id_3', 'id_4']

In [217]:
import pandas as pd

# Sample DataFrames for merge, concat, and join
df1 = pd.DataFrame({
    'key': ['A', 'B', 'C', 'D'],
    'value1': [1, 2, 3, 4]
})

df2 = pd.DataFrame({
    'key': ['C', 'D', 'E', 'F'],
    'value2': [5, 6, 7, 8]
})

df3 = pd.DataFrame({
    'key': ['A', 'B', 'X', 'Y'],
    'value3': [9, 10, 11, 12]
})

df_concat1 = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df_concat2 = pd.DataFrame({'col1': [5, 6], 'col2': [7, 8]})
df_concat3 = pd.DataFrame({'col3': [9, 10], 'col4': [11, 12]})


print("--- Original DataFrames ---")
print("df1:\n", df1)
print("\ndf2:\n", df2)
print("\ndf3:\n", df3)

--- Original DataFrames ---
df1:
   key  value1
0   A       1
1   B       2
2   C       3
3   D       4

df2:
   key  value2
0   C       5
1   D       6
2   E       7
3   F       8

df3:
   key  value3
0   A       9
1   B      10
2   X      11
3   Y      12


In [215]:

print("\ndf_concat1:\n", df_concat1)
print("\ndf_concat2:\n", df_concat2)
print("\ndf_concat3:\n", df_concat3)


df_concat1:
    col1  col2
0     1     3
1     2     4

df_concat2:
    col1  col2
0     5     7
1     6     8

df_concat3:
    col3  col4
0     9    11
1    10    12


In [212]:
# 1. merge example (similar to SQL JOIN)
print("\n--- pd.merge() Examples ---")
# Inner merge (default)
merged_inner = pd.merge(df1, df2, on='key', how='inner')
print("Inner Merge (on 'key'):\n", merged_inner)

# Outer merge
merged_outer = pd.merge(df1, df2, on='key', how='outer')
print("\nOuter Merge (on 'key'):\n", merged_outer)

# Left merge
merged_left = pd.merge(df1, df2, on='key', how='left')
print("\nLeft Merge (on 'key'):\n", merged_left)

# Right merge
merged_right = pd.merge(df1, df2, on='key', how='right')
print("\nRight Merge (on 'key'):\n", merged_right)



--- pd.merge() Examples ---
Inner Merge (on 'key'):
   key  value1  value2
0   C       3       5
1   D       4       6

Outer Merge (on 'key'):
   key  value1  value2
0   A     1.0     NaN
1   B     2.0     NaN
2   C     3.0     5.0
3   D     4.0     6.0
4   E     NaN     7.0
5   F     NaN     8.0

Left Merge (on 'key'):
   key  value1  value2
0   A       1     NaN
1   B       2     NaN
2   C       3     5.0
3   D       4     6.0

Right Merge (on 'key'):
   key  value1  value2
0   C     3.0       5
1   D     4.0       6
2   E     NaN       7
3   F     NaN       8


In [213]:
# 2. concat example (stacking DataFrames)
print("\n--- pd.concat() Examples ---")
# Concat rows (axis=0, default)
concatenated_rows = pd.concat([df_concat1, df_concat2])
print("Concatenated Rows:\n", concatenated_rows)

# Concat columns (axis=1)
concatenated_cols = pd.concat([df_concat1, df_concat3], axis=1)
print("\nConcatenated Columns:\n", concatenated_cols)

# Concat with ignore_index=True
concatenated_rows_reset_index = pd.concat([df_concat1, df_concat2], ignore_index=True)
print("\nConcatenated Rows (ignore_index=True):\n", concatenated_rows_reset_index)




--- pd.concat() Examples ---
Concatenated Rows:
    col1  col2
0     1     3
1     2     4
0     5     7
1     6     8

Concatenated Columns:
    col1  col2  col3  col4
0     1     3     9    11
1     2     4    10    12

Concatenated Rows (ignore_index=True):
    col1  col2
0     1     3
1     2     4
2     5     7
3     6     8


In [ ]:
# 3. join example (joining by index, or by column if specified)
print("\n--- df.join() Examples ---")
# Set 'key' as index for df1 and df3 for join operation
df1_indexed = df1.set_index('key')
df3_indexed = df3.set_index('key')

# Left join on index (default for df.join())
joined_left = df1_indexed.join(df3_indexed, how='left')
print("Left Join (on index):\n", joined_left)

# Inner join on index
joined_inner = df1_indexed.join(df3_indexed, how='inner')
print("\nInner Join (on index):\n", joined_inner)

# Join on a column (similar to merge with left_on/right_on)
# Re-create df1_indexed to avoid modifying it further for clarity
df1_indexed_for_join_on_col = df1.set_index('key')
df2_for_join_on_col = df2.set_index('key')
joined_on_column = df1_indexed_for_join_on_col.join(df2_for_join_on_col, how='inner')
print("\nJoin on column (by setting index first):\n", joined_on_column)


--- df.join() Examples ---
Left Join (on index):
      value1  value3
key                
A         1     9.0
B         2    10.0
C         3     NaN
D         4     NaN

Inner Join (on index):
      value1  value3
key                
A         1       9
B         2      10

Join on column (by setting index first):
      value1  value2
key                
C         3       5
D         4       6
